apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - ../grafana-dashboards-tke

helmCharts:
  - repo: https://prometheus-community.github.io/helm-charts
    name: kube-prometheus-stack
    releaseName: monitoring
    namespace: monitoring
    valuesFile: values.yaml
    includeCRDs: true
